#!/bin/sh

##########################################################################
 Alert for new migrations
##########################################################################
# Get list of files changed in migrations, replace spaces with newlines
new_migrations=$(git diff-tree --name-only -r ORIG_HEAD HEAD | grep migrations/ | tr " " "\n  ")

HIGHLIGHT='\033[0;31m' # red
NO_COLOR="\033[0m"

echo "\nChecking for new migrations we may need to pay attention to..."

if [ -n "$new_migrations" ]; then
        echo "${HIGHLIGHT}"
        printf '=%.0s' {1..80}
        echo "\nPlease pay special attention to these new migrations: \n"
        echo "${new_migrations}\n"
        printf '=%.0s' {1..80}
        echo " ${NO_COLOR} \n"
else
        echo "No migrations detected."
fi



##########################################################################
 Check bower and npm for updates
##########################################################################

# Modified from this version:
# http://www.gianlucaguarini.com/blog/how-to-sync-git-with-compass-npm-bower-composer-and-whatever-other-tool/

changed_files=$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)

on_file_change() {
    file=$(echo "$changed_files" | grep "$1")
    # If we found a file to change
    if [ -n "$file" ]; then
        folder=$(dirname $file)
        # Get into same dir as configuration file and execute command
        cd $folder && eval "$2"
    fi
}

on_file_change bower.json "bower install && bower update && bower prune"
on_file_change package.json "npm install && npm prune"

